---
- name: Create new EC2 instances
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    region:   "{{ region | default('us-west-2') }}"
    ami:      "{{ ami | default('you need to define this')  }}"
    keypair:  "{{ ec2_keypair_name | default('you need to define this') }}"
    set_dns:  False
    count:    1
    tags:
      env:  "{{ tags_env  | default('prod') }}"
      type: "{{ tags_type | default('web') }}"
    wait_for_ssh: True

  tasks:
    - name: Launch instance
      local_action:
        module: ec2
        keypair: "{{ keypair }}"
        instance_type: "{{ type | default('t2.micro') }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        image: "{{ ami }}"
        region: "{{ region }}"
        group: "{{ security_group | default('ssh-only') }}"
        count: "{{ count }}"
        wait: yes
        instance_tags: "{{ tags }}"
        user_data: "{{ lookup('template', 'ec2_bootstrap.j2') }}"
        assign_public_ip: "{{ assign_eip | default(true) }}"
      register: ec2

    - name: Instance info
      debug:
        msg: "{{ item.id }} {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
