- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
   - gce:
      instance_names: my-test-instance1
      machine_type: n1-standard-1
      image: debian-8
      state: present
      disk_size: 32
     register: instance
     
   - name: Wait for SSH to come up
     wait_for: host={{ instance.public_ip }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ instance.public_ip }} groupname=new_instances
