- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
   #- gce:
   #   instance_names: "{{ instance_names }}"
   #   machine_type: n1-standard-1
   #   image: "{{ image_name }}"
   #   state: present
   #   disk_size: 32
   #  register: gce
   
   - name: create a disk
     gcp_compute_disk:
      name: "disk-instance"
      size_gb: 25
      source_image: rhel-7-v20190423
      zone: us-east4-a
      project: "{{ gcp_project }}"
      state: present
      auth_kind: "serviceaccount"
      service_account_file: "/root/ansible-238814-f2a2d39a312f.json"
     register: disk
  
   - name: create a instance
     gcp_compute_instance:
      name: "test_object"
      machine_type: n1-standard-1
      disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
      network_interfaces:
      - subnetwork: us-east4-dev
      state: present
     register: gce
 
   - name: Save host data
     add_host:
       hostname: "{{ item.public_ip }}"
       groupname: gce_instances_ips
     with_items: "{{ gce.instance_data }}"

   - name: Wait for SSH for instances
     wait_for:
       delay: 1
       host: "{{ item.public_ip }}"
       port: 22
       state: started
       timeout: 30
     with_items: "{{ gce.instance_data }}"
